### ISSUE TITLE
Times out even when the site is live.

### ISSUE THREAD

**Issue by cloudlady911** [cec/wait-for-endpoint#1]
wait-for-endpoint.sh https://bakerfl.vetpro.us -s -t 30 -- echo "Test Completed"
wait-for-endpoint.sh: waiting 30 seconds for https://bakerfl.vetpro.us
wait-for-endpoint.sh: timeout occurred after waiting 30 seconds for https://bakerfl.vetpro.us
wait-for-endpoint.sh: strict mode, refusing to execute subprocess

I have a monitoring system the also monitors my websites.  It shows Status Code 200 in its test results, with a response time of 84ms.

running on ubuntu 16.

**Comment by cec** [comment]
Hi @cloudlady911 ,

doing `curl -v https://bakerfl.vetpro.us` I get `HTTP/1.1 303 See Other`

As described in the first line of the README, this script expects a 200 response.

Is there another URL you could use that returns a 200?

The /healtcheck endpoint of all my APIs return 200, that's why I didn't add a flag to specify a different expected response code.

If you need this feature soon, it would be really great if you made a PR adding this feature :)
